# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('publisher_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
